//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public Building()
        {
            this.Pis = new HashSet<Pi>();
        }
    
        public System.Guid BuildingId { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<Pi> Pis { get; set; }
    }
}
