//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTester.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pi
    {
        public Pi()
        {
            this.Readings = new HashSet<Reading>();
        }
    
        public System.Guid PiId { get; set; }
        public string Name { get; set; }
        public System.Guid BuildingId { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual ICollection<Reading> Readings { get; set; }
    }
}
